resource_types:
 - name: yo-bell-oti
   type: docker-image
   source:
     repository: 4ttilio/geo-resource

resources:
  - name: shirely
    type: yo-bell-oti

jobs:
  - name: shirely-test
    plan:
    - get: shirely
      trigger: true
    - task: test
      config:
        image_resource:
          type: docker-image
          source: { repository: busybox }
        platform: linux
        inputs:
        - name: shirely
        run:
          path: echo
          args:
          - "hello shirely"
